import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import AuthProvider from "@/context/AuthProvider";
import ReduxProvider from "@/context/ReduxProvider";
import AppInitializer from "./checkUserLogin/AppInitializer";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ReduxProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <AppInitializer />
            <Navbar />
            {children}
            <Toaster />
          </body>
        </ReduxProvider>
      </AuthProvider>
    </html>
  );
}
